
IF
OnCreation()
GlobalLT("PI#Ka1","GLOBAL",1)
THEN RESPONSE #100
SetGlobal("PI#Ka1","GLOBAL",1)
StartCutScene("PI#Kal")
END

IF
Global("PI#Ka1","GLOBAL",2)
THEN RESPONSE #100
DisplayStringHead(Player1,@0)
Wait(10)
CreateCreature("pi#sha2",[800.400],12)
CreateCreature("pi#sha2",[300.750],12)
CreateCreature("pi#sha2",[950.800],12)
CreateCreature("pi#sha2",[400.400],12)
CreateCreature("pi#sha2",[800.400],12)
CreateCreature("pi#sha2",[300.750],12)
CreateCreature("pi#sha2",[950.800],12)
CreateCreature("pi#sha2",[400.400],12)
CreateCreature("pi#sha2",[800.400],12)
CreateCreature("pi#sha2",[300.750],12)
CreateCreature("pi#sha2",[950.800],12)
CreateCreature("pi#sha2",[400.400],12)

Wait(8)
SetGlobal("PI#Ka1","GLOBAL",3)
END

IF
Global("PI#Ka1","GLOBAL",3)
THEN RESPONSE #100
DisplayStringHead(Player1,@1)
Wait(2)
CreateCreature("pi#sha2",[800.400],12)
CreateCreature("pi#sha2",[300.750],12)
CreateCreature("pi#sha2",[950.800],12)
CreateCreature("pi#sha2",[400.400],12)
CreateCreature("pi#sha2",[800.400],12)
CreateCreature("pi#sha2",[300.750],12)
CreateCreature("pi#sha2",[950.800],12)
CreateCreature("pi#sha2",[400.400],12)
Wait(8)
SetGlobal("PI#Ka1","GLOBAL",4)
END

IF
Global("PI#Ka1","GLOBAL",4)
THEN RESPONSE #100
DisplayStringHead(Player1,@1)
Wait(2)
CreateCreature("KSHADOW",[800.400],12)
CreateCreature("KSHADOW",[300.750],12)
CreateCreature("KSHADOW",[950.800],12)
CreateCreature("KSHADOW",[400.400],12)
Wait(5)
SetGlobal("PI#Ka1","GLOBAL",5)
END

IF
Global("PI#Ka1","GLOBAL",5)
THEN RESPONSE #100
DisplayStringHead(Player1,@1)
Wait(2)
CreateCreature("KSHADOW",[800.400],12)
CreateCreature("KSHADOW",[300.750],12)
CreateCreature("KSHADOW",[950.800],12)
CreateCreature("KSHADOW",[400.400],12)
Wait(5)
SetGlobal("PI#Ka1","GLOBAL",6)
END


IF
Global("PI#Ka1","GLOBAL",6)
THEN RESPONSE #100
DisplayStringHead(Player1,@2)
Wait(5)
CreateCreature("KSHADOW",[800.400],12)
CreateCreature("KSHADOW",[300.750],12)
CreateCreature("KSHADOW",[950.800],12)
CreateCreature("KSHADOW",[400.400],12)
Wait(5)
SetGlobal("PI#Ka1","GLOBAL",7)
END

IF
CombatCounter(0)
Global("PI#Ka1","GLOBAL",7)
THEN RESPONSE #100
StartCutScene("PI#kal3")
END

